version: 2.1
workflows:
  version: 2
  build_push_test:
    jobs:      
      - backup_test_env
      - pantheon/push
orbs:
  pantheon: pantheon-systems/pantheon@0.2.0 
jobs:
  backup_test_env:
    docker:
    - image: quay.io/pantheon-public/build-tools-ci:5.x
    steps:
    - run:
       name: Set PR number
       command: |
         echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
         source $BASH_ENV
         echo $CIRCLE_PR_NUMBER
    - run:
        name: 'Setup env variables'
        command: |
          echo 'export MY_PR_NUMBER="$CIRCLE_PR_NUMBER"' >> $BASH_ENV
          echo 'export MY_PR_NUMBER2=${CIRCLE_PULL_REQUEST##*/}' >> $BASH_ENV
          echo 'export MY_PR="$CIRCLE_PULL_REQUEST"' >> $BASH_ENV
    - run:
        name: 'What PR am I on?'
        command: echo $MY_PR
    - run:
        name: 'What is my PR number?'
        command: echo $MY_PR_NUMBER
    - run:
        name: 'What is my PR number2?'
        command: echo $MY_PR_NUMBER2
